import { Bot, CheckCircle2, CircleAlert, Database, Fingerprint, ServerCog, ShieldCheck } from "lucide-react";
import Link from "next/link";

type Status = Awaited<ReturnType<typeof import("@/lib/server/repository")["getSystemStatus"]>>;
function Control({ icon: Icon, label, ok, detail }: { icon: typeof Database; label: string; ok: boolean; detail: string }) {
  return <article className={`system-control${ok ? " is-ready" : " is-pending"}`}><div className="system-control-icon"><Icon size={17} /></div><div><span>{label}</span><strong>{ok ? "Ready" : "Needs configuration"}</strong><p>{detail}</p></div>{ok ? <CheckCircle2 size={17} /> : <CircleAlert size={17} />}</article>;
}
export function SystemStatus({ status }: { status: Status }) {
  const productionReady = status.databaseReachable && status.identity && status.mlServiceReachable;
  return <section className="system-status-board"><header><div><span className="eyebrow">Production control plane</span><h1>{productionReady ? "Systems ready for live review" : "Complete the production connection"}</h1><p>LoanPulse checks each dependency without exposing credentials or connection details.</p></div><div className={`readiness-orbit${productionReady ? " is-ready" : ""}`}><i /><strong>{productionReady ? "READY" : status.mode.toUpperCase()}</strong><small>{new Date(status.checkedAt).toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata" })}</small></div></header><div className="system-control-grid"><Control icon={Database} label="Neon data plane" ok={status.databaseReachable} detail={status.databaseReachable ? `Connected · ${status.databaseLatencyMs} ms check` : "Add DATABASE_URL and run the migration and seed commands."} /><Control icon={Fingerprint} label="Reviewer identity" ok={status.identity} detail={status.identity ? "Clerk session and role enforcement configured." : "Add Clerk publishable and secret keys."} /><Control icon={ServerCog} label="ML inference service" ok={status.mlServiceReachable} detail={status.mlServiceReachable ? `Artifact loaded · ${status.mlServiceLatencyMs} ms check` : status.mlService ? "Configured, but readiness check failed." : "Deploy the Python service and add its URL and API key."} /><Control icon={Bot} label="Reviewer copilot" ok={status.copilot} detail={status.copilot ? "Gemini server integration configured." : "Optional: add GEMINI_API_KEY for advisory summaries."} /><Control icon={ShieldCheck} label="Immutable audit" ok={status.databaseReachable} detail={status.databaseReachable ? "Hash chain and mutation-blocking trigger available." : "Audit persistence activates with the Neon migration."} /></div><div className="setup-ledger"><div><span>01</span><p><strong>Connect Neon</strong><small>Add pooled and direct URLs to <code>.env.local</code>.</small></p><code>npm run db:setup</code></div><div><span>02</span><p><strong>Connect identity</strong><small>Add Clerk keys and list administrator emails.</small></p><code>APP_MODE=production</code></div><div><span>03</span><p><strong>Deploy inference</strong><small>Build the ML container from the validated artifact.</small></p><code>docker compose up ml</code></div></div><footer><span>Readiness endpoint: <code>/api/ready</code></span><Link href="/controls">Review policy controls →</Link></footer></section>;
}
